-- 게시판 테이블
DROP TABLE IF EXISTS board;
CREATE TABLE board(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(40) NOT NULL,
	category VARCHAR(15) NOT NULL,
	title VARCHAR(80) NOT NULL,
	content TEXT NOT NULL,
	writer VARCHAR(20) NOT NULL,
	hits INT NOT NULL DEFAULT 0,
	regdate DATETIME
);

-- 댓글 테이블
DROP TABLE IF EXISTS reply;
CREATE TABLE reply(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	bid INT NOT NULL,
	content TEXT NOT NULL,
	writer VARCHAR(20) NOT NULL,
	regdate DATETIME,
	FOREIGN KEY(bid) REFERENCES board(id)
	ON UPDATE CASCADE ON DELETE CASCADE
);