-- 장바구니 테이블
DROP TABLE IF EXISTS cart;
CREATE TABLE cart(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	pid INT NOT NULL,
	email VARCHAR(40) NOT NULL,
	pname VARCHAR(30) NOT NULL,
	price INT NOT NULL,
	qty INT NOT NULL DEFAULT 1,
	img VARCHAR(255),
	regdate DATETIME,
	FOREIGN KEY(pid) REFERENCES product(id)
	ON UPDATE CASCADE ON DELETE CASCADE
);
