-- 스토어 테이블
DROP TABLE IF EXISTS store;
CREATE TABLE store(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	storename VARCHAR(15) NOT NULL,
	president VARCHAR(20) NOT NULL,
	addr1 VARCHAR(100) NOT NULL,
	tel CHAR(13) NOT NULL,
	regdate DATETIME
);
